openapi: 3.1.0
info:
  title: Category API
  description: Category API
  version: 1.0.0

paths:
  /api/v1/categories:
    get:
      summary: Get all categories
      tags:
        - Category
      responses:
        200:
          description: List of all categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'

  /api/v1/categories/{id}:
    get:
      summary: Get category by ID
      tags:
        - Category
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the category
      responses:
        200:
          description: Category found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'
        404:
          description: Category not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
          description: URI reference identifying the error type
        title:
          type: string
          description: A short description of the error
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Detailed description of the error

    CategoryDto:
      type: object
      properties:
        title:
          type: string
          description: Title of the category (must include specific keywords and cannot exceed 50 characters)
          maxLength: 100
        description:
          type: string
          description: Detailed description of the category (cannot exceed 255 characters)
          maxLength: 255